services:
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  django:
    build:
      context: ..
      dockerfile: ./docker/django/Dockerfile-django
    env_file:
      - ../.env
    image: django
    container_name: django
    ports:
      - "8000:8000"
    volumes: 
      - django:/app
    networks:
      - app-network
    restart: on-failure
    depends_on:
      postgresql:
        condition: service_healthy

volumes:
  postgresql:
    name: Transcendence_postgresql
    driver: local
    driver_opts:
      type: none
      device: ../postgresql-data
      o: bind
  django:
    name: Transcendence_django
    driver: local
    driver_opts:
      type: none
      device: ../django
      o: bind

networks:
  app-network:
    driver: bridge
    name: Transcendence_network